#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.11
# In conjunction with Tcl version 8.6
#    Apr 16, 2018 08:12:29 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import pdgs_support
import dnd
from dnd import DndHandler
from dnd import Icon
from dnd import Tester

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel (root)
    pdgs_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel (w)
    pdgs_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("961x528+300+164")
        top.title("New Toplevel")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.lab38 = Label(top)
        self.lab38.place(relx=0.0, rely=0.0, height=31, width=384)
        self.lab38.configure(activebackground="#f9f9f9")
        self.lab38.configure(activeforeground="black")
        self.lab38.configure(background="#ffffff")
        self.lab38.configure(disabledforeground="#a3a3a3")
        self.lab38.configure(font="none 16 bold")
        self.lab38.configure(foreground="#FF6600")
        self.lab38.configure(highlightbackground="#d9d9d9")
        self.lab38.configure(highlightcolor="black")
        self.lab38.configure(text='''Protocol Dissector Generator System''')
        self.lab38.configure(width=384)

        self.Button1 = Button(top)
        self.Button1.place(relx=0.0, rely=0.06, height=24, width=85)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=pdgs_support.create_window)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(relief=GROOVE)
        self.Button1.configure(text='''Create Project''')

        self.Button2 = Button(top)
        self.Button2.place(relx=0.2, rely=0.06, height=24, width=80)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(relief=GROOVE)
        self.Button2.configure(text='''Close Project''')

        self.Button3 = Button(top)
        self.Button3.place(relx=0.52, rely=0.06, height=24, width=84)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(command=pdgs_support.export)
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(relief=GROOVE)
        self.Button3.configure(text='''Export Project''')

        self.Button4 = Button(top)
        self.Button4.place(relx=0.62, rely=0.06, height=24, width=142)
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#d9d9d9")
        self.Button4.configure(command=pdgs_support.dissectorScript)
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(relief=GROOVE)
        self.Button4.configure(text='''Generate Dissector Script''')

        self.Button5 = Button(top)
        self.Button5.place(relx=0.78, rely=0.06, height=24, width=91)
        self.Button5.configure(activebackground="#d9d9d9")
        self.Button5.configure(activeforeground="#000000")
        self.Button5.configure(background="#d9d9d9")
        self.Button5.configure(command=pdgs_support.organize_views)
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(pady="0")
        self.Button5.configure(relief=GROOVE)
        self.Button5.configure(text='''Organize Views''')

        self.Button6 = Button(top)
        self.Button6.place(relx=0.29, rely=0.06, height=24, width=107)
        self.Button6.configure(activebackground="#d9d9d9")
        self.Button6.configure(activeforeground="#000000")
        self.Button6.configure(background="#d9d9d9")
        self.Button6.configure(command=pdgs_support.launcher_window)
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        self.Button6.configure(pady="0")
        self.Button6.configure(relief=GROOVE)
        self.Button6.configure(text='''Switch Workspace''')

        self.Button7 = Button(top)
        self.Button7.place(relx=0.42, rely=0.06, height=24, width=87)
        self.Button7.configure(activebackground="#d9d9d9")
        self.Button7.configure(activeforeground="#000000")
        self.Button7.configure(background="#d9d9d9")
        self.Button7.configure(command=pdgs_support.project_import)
        self.Button7.configure(disabledforeground="#a3a3a3")
        self.Button7.configure(foreground="#000000")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="black")
        self.Button7.configure(pady="0")
        self.Button7.configure(relief=GROOVE)
        self.Button7.configure(text='''Import Project''')

        self.Button8 = Button(top)
        self.Button8.place(relx=0.1, rely=0.06, height=24, width=75)
        self.Button8.configure(activebackground="#d9d9d9")
        self.Button8.configure(activeforeground="#000000")
        self.Button8.configure(background="#d9d9d9")
        self.Button8.configure(disabledforeground="#a3a3a3")
        self.Button8.configure(foreground="#000000")
        self.Button8.configure(highlightbackground="#d9d9d9")
        self.Button8.configure(highlightcolor="black")
        self.Button8.configure(pady="0")
        self.Button8.configure(relief=GROOVE)
        self.Button8.configure(text='''Save Project''')

        self.Button9 = Button(top)
        self.Button9.place(relx=0.88, rely=0.06, height=24, width=73)
        self.Button9.configure(activebackground="#d9d9d9")
        self.Button9.configure(activeforeground="#000000")
        self.Button9.configure(background="#d9d9d9")
        self.Button9.configure(command=pdgs_support.vp_start)
        self.Button9.configure(disabledforeground="#a3a3a3")
        self.Button9.configure(foreground="#000000")
        self.Button9.configure(highlightbackground="#d9d9d9")
        self.Button9.configure(highlightcolor="black")
        self.Button9.configure(pady="0")
        self.Button9.configure(relief=GROOVE)
        self.Button9.configure(text='''Open PCAP''')

        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg='#ffffff')
        top.configure(menu = self.menubar)



        self.Frame2 = Frame(top)
        self.Frame2.place(relx=0.0, rely=0.11, relheight=0.86, relwidth=0.18)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(background="#d9d9d9")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")
        self.Frame2.configure(width=175)

        self.Label1 = Label(self.Frame2)
        self.Label1.place(relx=0.0, rely=0.01, height=41, relwidth=1)
        self.Label1.configure(background="#C0D5E7")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="none 12 bold")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Project Navigator''')
        self.Label1.configure(width=168)

        self.TSizegrip2 = ttk.Sizegrip(self.Frame2)
        self.TSizegrip2.place(anchor=SE, relx=1.0, rely=1.0)

        self.Frame3 = Canvas(top)
        self.Frame3.place(relx=0.19, rely=0.11, relheight=0.63, relwidth=0.79)
        self.Frame3.configure(relief=GROOVE)
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief=GROOVE)
        self.Frame3.configure(background="#d9d9d9")
        self.Frame3.configure(highlightbackground="#d9d9d9")
        self.Frame3.configure(highlightcolor="black")
        self.Frame3.configure(width=755)

        self.Label2 = Label(self.Frame3)
        self.Label2.place(relx=0.0, rely=0.0, height=41, relwidth=1)
        self.Label2.configure(background="#C0D5E7")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="none 12 bold")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Dissector Builder Area''')
        self.Label2.configure(width=745)

        self.Frame5 = Frame(top)
        self.Frame5.place(relx=0.65, rely=0.12, relheight=0.85, relwidth=0.35)
        self.Frame5.configure(relief=GROOVE)
        self.Frame5.configure(borderwidth="2")
        self.Frame5.configure(relief=GROOVE)
        self.Frame5.configure(background="#d9d9d9")
        self.Frame5.configure(width=195)

        self.Label3 = Label(self.Frame5)
        self.Label3.place(relx=0.0, rely=0.0, height=31, relwidth=1)
        self.Label3.configure(background="#C0D5E7")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font="none 12 bold")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Palette''')
        self.Label3.configure(width=194)
        

        self.startButton = Button(self.Frame5)
        self.startButton.place(relx=0.07, rely=0.2, height=33, width=76)
        self.startButton.configure(background="#d9d9d9")
        self.startButton.configure(pady="0")
        self.startButton.configure(relief=GROOVE)
        self.startButton.configure(text='''Start Field''')
        self.startButton.configure(width=76)

        self.byte2Button = Button(self.Frame5)
        self.byte2Button.place(relx=0.07, rely=0.32, height=33, width=96)
        self.byte2Button.configure(background="#d9d9d9")
        self.byte2Button.configure(pady="0")
        self.byte2Button.configure(relief=GROOVE)
        self.byte2Button.configure(text='''Field (2 byte)''')
        self.byte2Button.configure(width=96)

        self.byte8Button = Button(self.Frame5)
        self.byte8Button.place(relx=0.07, rely=0.43, height=33, width=96)
        self.byte8Button.configure(background="#d9d9d9")
        self.byte8Button.configure(pady="0")
        self.byte8Button.configure(relief=GROOVE)
        self.byte8Button.configure(text='''Field (8 byte)''')

        self.byte82Button = Button(self.Frame5)
        self.byte82Button.place(relx=0.07, rely=0.55, height=33, width=96)
        self.byte82Button.configure(background="#d9d9d9")
        self.byte82Button.configure(pady="0")
        self.byte82Button.configure(relief=GROOVE)
        self.byte82Button.configure(text='''Field (8 byte)''')

        self.varSizeButton = Button(self.Frame5)
        self.varSizeButton.place(relx=0.07, rely=0.67, height=33, width=106)
        self.varSizeButton.configure(background="#d9d9d9")
        self.varSizeButton.configure(pady="0")
        self.varSizeButton.configure(relief=GROOVE)
        self.varSizeButton.configure(text='''Field (Var Size)''')
        self.varSizeButton.configure(width=106)

        self.referenceButton = Button(self.Frame5)
        self.referenceButton.place(relx=0.07, rely=0.78, height=33, width=106)
        self.referenceButton.configure(background="#d9d9d9")
        self.referenceButton.configure(pady="0")
        self.referenceButton.configure(relief=GROOVE)
        self.referenceButton.configure(text='''Reference List''')
        self.referenceButton.configure(width=106)

        self.byte1Button = Button(self.Frame5)
        self.byte1Button.place(relx=0.55, rely=0.2, height=33, width=96)
        self.byte1Button.configure(background="#d9d9d9")
        self.byte1Button.configure(pady="0")
        self.byte1Button.configure(relief=GROOVE)
        self.byte1Button.configure(text='''Field (1 byte)''')

        self.byte4Button = Button(self.Frame5)
        self.byte4Button.place(relx=0.55, rely=0.32, height=33, width=96)
        self.byte4Button.configure(background="#d9d9d9")
        self.byte4Button.configure(pady="0")
        self.byte4Button.configure(relief=GROOVE)
        self.byte4Button.configure(text='''Field (4 byte)''')

        self.byte16Button = Button(self.Frame5)
        self.byte16Button.place(relx=0.55, rely=0.43, height=33, width=106)
        self.byte16Button.configure(background="#d9d9d9")
        self.byte16Button.configure(pady="0")
        self.byte16Button.configure(relief=GROOVE)
        self.byte16Button.configure(text='''Field (16 byte)''')
        self.byte16Button.configure(width=106)

        self.byte162Button = Button(self.Frame5)
        self.byte162Button.place(relx=0.55, rely=0.55, height=33, width=106)
        self.byte162Button.configure(background="#d9d9d9")
        self.byte162Button.configure(pady="0")
        self.byte162Button.configure(relief=GROOVE)
        self.byte162Button.configure(text='''Field (16 byte)''')
        self.byte162Button.configure(width=106)

        self.endButton = Button(self.Frame5)
        self.endButton.place(relx=0.55, rely=0.67, height=33, width=96)
        self.endButton.configure(background="#d9d9d9")
        self.endButton.configure(pady="0")
        self.endButton.configure(relief=GROOVE)
        self.endButton.configure(text='''End Field''')

        self.pInfoButton = Button(self.Frame5)
        self.pInfoButton.place(relx=0.55, rely=0.78, height=33, width=96)
        self.pInfoButton.configure(background="#d9d9d9")
        self.pInfoButton.configure(pady="0")
        self.pInfoButton.configure(relief=GROOVE)
        self.pInfoButton.configure(text='''Packet Info.''')

        self.TSizegrip1 = ttk.Sizegrip(self.Frame3)
        self.TSizegrip1.place(anchor=SE, relx=1.0, rely=1.0)

        self.Frame4 = Frame(top)
        self.Frame4.place(relx=0.19, rely=0.76, relheight=0.22, relwidth=0.79)
        self.Frame4.configure(relief=GROOVE)
        self.Frame4.configure(borderwidth="2")
        self.Frame4.configure(relief=GROOVE)
        self.Frame4.configure(background="#d9d9d9")
        self.Frame4.configure(highlightbackground="#d9d9d9")
        self.Frame4.configure(highlightcolor="black")
        self.Frame4.configure(width=755)

        self.TSizegrip3 = ttk.Sizegrip(self.Frame4)
        self.TSizegrip3.place(anchor=SE, relx=1.0, rely=1.0)

        self.Frame1 = Frame(self.Frame4)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=0.23)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(width=175)

        self.Label4 = Label(self.Frame1)
        self.Label4.place(relx=0.0, rely=0.01, height=21, relwidth=1)
        self.Label4.configure(background="#C0D5E7")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font="none 10 bold")
        self.Label4.configure(foreground="#ffffff")
        self.Label4.configure(text='''Packet Stream Area''')
        self.Label4.configure(width=174)

        self.Frame6 = Frame(self.Frame4)
        self.Frame6.place(relx=0.23, rely=0.0, relheight=1.0, relwidth=0.26)
        self.Frame6.configure(relief=GROOVE)
        self.Frame6.configure(borderwidth="2")
        self.Frame6.configure(relief=GROOVE)
        self.Frame6.configure(background="#d9d9d9")
        self.Frame6.configure(width=195)

        self.Label5 = Label(self.Frame6)
        self.Label5.place(relx=0.0, rely=0.01, height=21, relwidth=1)
        self.Label5.configure(background="#C0D5E7")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font="none 10 bold")
        self.Label5.configure(foreground="#ffffff")
        self.Label5.configure(text='''Dissected Stream Area''')
        self.Label5.configure(width=194)

        self.Frame7 = Frame(self.Frame4)
        self.Frame7.place(relx=0.48, rely=0.0, relheight=1.0, relwidth=0.26)
        self.Frame7.configure(relief=GROOVE)
        self.Frame7.configure(borderwidth="2")
        self.Frame7.configure(relief=GROOVE)
        self.Frame7.configure(background="#d9d9d9")
        self.Frame7.configure(width=195)

        self.Label6 = Label(self.Frame7)
        self.Label6.place(relx=0.0, rely=0.01, height=22, relwidth=1)
        self.Label6.configure(background="#C0D5E7")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font="none 10 bold")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(text='''Raw Data Area''')
        self.Label6.configure(width=191)

        self.Frame8 = Frame(self.Frame4)
        self.Frame8.place(relx=0.74, rely=0.0, relheight=1.0, relwidth=0.26)
        self.Frame8.configure(relief=GROOVE)
        self.Frame8.configure(borderwidth="2")
        self.Frame8.configure(relief=GROOVE)
        self.Frame8.configure(background="#d9d9d9")
        self.Frame8.configure(width=195)

        self.Label7 = Label(self.Frame8)
        self.Label7.place(relx=0.0, rely=0.01, height=22, relwidth=1)
        self.Label7.configure(background="#C0D5E7")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(font="none 10 bold")
        self.Label7.configure(foreground="#ffffff")
        self.Label7.configure(text='''Console Area''')
        self.Label7.configure(width=191)
        
        
        #dnd.dnd_start(self.startButton,"<Button-1>")
        t1 = Tester(self.Frame5)
        t2 = Tester(self.Frame3)
        start = Icon("Start")
        field2 = Icon("Field (2 byte)")
        field8 = Icon("Field (8 byte)")
        field82 = Icon("Field (8 byte)")
        fieldvar = Icon("Field (Var Size)")
        reference = Icon("Reference List")
        field1 = Icon("Field (1 byte)")
        field4 = Icon("Field (4 byte)")
        field16 = Icon("Field (16 byte)")
        field162 = Icon("Field (16 byte)")
        end = Icon("End Field")
        info = Icon("Packet Info.")
        start.attach(t1.canvas)
        field2.attach(t1.canvas, y=40)
        field8.attach(t1.canvas,y=70)
        field82.attach(t1.canvas,y=100)
        fieldvar.attach(t1.canvas,y=130)
        reference.attach(t1.canvas,y=160)
        field1.attach(t1.canvas,x=200)
        field4.attach(t1.canvas,x=200,y=40)
        field16.attach(t1.canvas,x=200,y=70)
        field162.attach(t1.canvas,x=200,y=100)
        end.attach(t1.canvas,x=200,y=130)
        info.attach(t1.canvas,x=200,y=160)
        



if __name__ == '__main__':
    vp_start_gui()



